# Site settings
livereload: true
title: PrimeTimeTran
email: datloiboi@gmail.com
url: https://github.com/PrimeTimeTran
description: "Professional software developer, Loi Tran is a Solutions Architect with over 5 years of professional development experience. He specializes in Node, React, React Native, Electron, &  Ruby on Rails."
keywords: "Solution Architect, Solutions Architect, Node.Js, React.JS, ReactJS, React, React Native, Ruby on Rails in Ho Chi Minh City, Vietnam. Outsourcing, Freelancer"
skills: "Developer - Instructor - Student"
meta_author: Loi Van Tran

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: PrimeTimeTran

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: <a href="https://www.primetimetran.com"> PrimeTimeTran</a>
  location: Location
  social: Web
  about: About

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: github
    url: https://github.com/PrimeTimeTran
  - title: linkedin
    url: https://www.linkedin.com/in/primetimetran/
  - title: youtube-play
    url: https://www.youtube.com/channel/UCGh6HQz-nRtdqTxP1CiFFlg
  - title: stack-overflow
    url: https://stackoverflow.com/users/5451285/primetimetran
  - title: facebook-square
    url: https://www.facebook.com/PrimeTimeTran/

# Postal address (add as many lines as necessary)
address:
  - line: District 1,
  - line: HCMC, Vietnam

# About content
about: 'This is a technology blog for those interested in <a href="https://nodejs.org/en/">Node.JS</a>, <a href="https://reactjs.org/">React.JS</a>, <a href="https://reactnative.dev/">React Native</a>, <a href="https://www.electronjs.org/">Electron</a>, <a href="https://rubyonrails.org/">Ruby on Rails</a> & much more.'

# Build settings
markdown: kramdown
permalink: pretty

# for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
      excerpt_separator: <!--more-->